version: "2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - 'sh'
      - '-c'
      - 'yarn install && yarn watch'
    volumes:
      - .:/src/app/
      - /src/app/node_modules
    environment:
      AUTH0_DOMAIN: wedding-dev.us.auth0.com
      AUTH0_CLIENT_ID: TBJcmSMNSi2hyyFGr7DtNoahDNbRNLHg
      AUTH0_SECRET: 8ykISGoIMsm79cA9AaCQ0EYr-Ro34pAfGUd9Va-CvCnw-C62TWytzyPRo5zB6Zsm
      JWT_SECRET: D(G+KbPeShVmYq3t6w9z$B&E)H@McQfT
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  data:
    driver: local